"""empty message

Revision ID: 31b96d31f3f8
Revises: b6a276249599
Create Date: 2025-06-24 10:46:06.204704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31b96d31f3f8'
down_revision = 'b6a276249599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))

    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.drop_column('notification_sent_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
