"""Initial migration with all models

Revision ID: b6a276249599
Revises: 
Create Date: 2025-06-18 20:47:06.889770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a276249599'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('town', sa.String(length=100), nullable=True),
    sa.Column('level_of_education', sa.String(length=100), nullable=True),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('religion', sa.String(length=100), nullable=True),
    sa.Column('ethnicity', sa.String(length=100), nullable=True),
    sa.Column('self_description', sa.Text(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('registration_stage', sa.Enum('ACTIVATED', 'INITIAL', 'DETAILS_PENDING', 'DESCRIPTION_PENDING', 'COMPLETED', name='registrationstage'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('match_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age_min', sa.Integer(), nullable=False),
    sa.Column('age_max', sa.Integer(), nullable=False),
    sa.Column('preferred_town', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'completed')", name='check_status'),
    sa.CheckConstraint('age_min <= age_max', name='check_age_range'),
    sa.CheckConstraint('age_min >= 18', name='check_min_age'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_phone', sa.String(length=15), nullable=True),
    sa.Column('to_phone', sa.String(length=15), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interested_user_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('interest_type', sa.String(length=20), server_default='details', nullable=False),
    sa.Column('notification_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('response_received', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('response', sa.String(length=10), nullable=True),
    sa.Column('response_at', sa.DateTime(), nullable=True),
    sa.Column('feedback_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("interest_type IN ('details', 'describe')", name='check_interest_type'),
    sa.CheckConstraint("response IN ('YES', 'NO') OR response IS NULL", name='check_response'),
    sa.ForeignKeyConstraint(['interested_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('matched_user_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['matched_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['match_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('user_interests')
    op.drop_table('sms_messages')
    op.drop_table('match_requests')
    op.drop_table('users')
    # ### end Alembic commands ###
